### ISSUE TITLE
License missing in source tree

### ISSUE THREAD

**Issue by vishalvvr** [mosquito/python-pidfile#10]
Hello, 
I am packaging this project into fedora, so the main concern raised is which license does this project follow?

This is the comment on the fedora packaging ticket
```
It's not clear which MIT license variant this package will be using. 
Maybe ask upstream to add the license text in upstream code or ask them to is this project follows 
https://fedoraproject.org/wiki/Licensing:MIT?rd=Licensing/MIT#Modern_Style_with_sublicense 
or 
https://fedoraproject.org/wiki/Licensing/MIT-0 license.
``` 

[1] https://bugzilla.redhat.com/show_bug.cgi?id=2130496

**Comment by mosquito** [comment]
You could choose what you want and create PR with it. 😀
